# Generated by Django 5.1 on 2024-11-14 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixthSense', '0003_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAuditList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_preparer', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('year', models.IntegerField()),
                ('missing_documents', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('taxpayer_name', models.CharField(max_length=255)),
                ('identification_drivers_license', models.BooleanField(default=False)),
                ('social_security_card', models.BooleanField(default=False)),
                ('healthcare1095_form', models.BooleanField(default=False)),
                ('spouse_name', models.CharField(blank=True, max_length=255, null=True)),
                ('identification_drivers_license1', models.BooleanField(default=False)),
                ('social_security_card1', models.BooleanField(default=False)),
                ('healthcare1095_form1', models.BooleanField(default=False)),
                ('a_of_dependents', models.BooleanField(default=False)),
                ('dependent_ssc', models.BooleanField(default=False)),
                ('healthcare_card', models.BooleanField(default=False)),
                ('birth_certificate', models.BooleanField(default=False)),
                ('application_w_signature', models.BooleanField(default=False)),
                ('signed_documents', models.BooleanField(default=False)),
                ('w2', models.BooleanField(default=False)),
                ('self_employment_log', models.BooleanField(default=False)),
                ('a1099', models.BooleanField(default=False)),
                ('ssa', models.BooleanField(default=False)),
                ('a1098t', models.BooleanField(default=False)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_company_ids', to='sixthSense.company')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_lists', to='sixthSense.company')),
                ('preparer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_lists', to='sixthSense.preparer')),
            ],
        ),
    ]
