# Generated by Django 5.1 on 2024-11-15 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixthSense', '0004_clientauditlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_preparer', models.TextField(blank=True, null=True)),
                ('taxpayer_first_name', models.CharField(max_length=100)),
                ('taxpayer_last_name', models.CharField(max_length=100)),
                ('total_prep_fee_charged', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fees_intercepted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_prep_fee_deposited', models.DecimalField(decimal_places=2, max_digits=10)),
                ('funding_date', models.DateField()),
                ('year', models.IntegerField()),
                ('partnership_remaining_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance_loan_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sum_total_preparer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('split', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prior_week_hold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_week_hold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_hold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('release_hold_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dd_confirmed', models.BooleanField(default=False)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts_by_id', to='sixthSense.company')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts_by_name', to='sixthSense.company')),
                ('preparer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='sixthSense.preparer')),
            ],
        ),
    ]
