# Generated by Django 5.1 on 2024-11-15 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixthSense', '0006_taxpayerloanstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebReportTaxesToGo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_preparer', models.TextField(blank=True, null=True)),
                ('group_name', models.IntegerField()),
                ('efin', models.IntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('cell_phone', models.CharField(max_length=15)),
                ('referral_code', models.CharField(max_length=100)),
                ('app_submit_date', models.DateField()),
                ('referrer', models.DateField(blank=True, null=True)),
                ('validation_code', models.IntegerField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_reports_by_id', to='sixthSense.company')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_reports_by_name', to='sixthSense.company')),
                ('preparer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_reports', to='sixthSense.preparer')),
            ],
        ),
    ]
