# Generated by Django 5.1 on 2024-11-15 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixthSense', '0007_webreporttaxestogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='web_reports/')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_reports', to='sixthSense.company')),
            ],
        ),
    ]
