# Generated by Django 5.1 on 2024-11-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sixthSense', '0009_rename_agt_irs_agree_date_preparer_agree_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='company_id',
        ),
    ]
