# Generated by Django 5.1 on 2024-11-19 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sixthSense', '0010_remove_client_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientauditlist',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='payoutbreakdown',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='webreporttaxestogo',
            name='company_id',
        ),
    ]
